[project]
name = "orgDBLP"
version = "0.3"

[project.scripts]
orgDBLP_query = "orgDBLP.scripts.main:main_cli"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["orgDBLP","orgDBLP.scripts"]


